ESchool/ESchool.Web/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ESchool.Services.Constants;
using ESchool.Services.Contracts;
using ESchool.ViewModels.InputModels.Answer;
using ESchool.ViewModels.InputModels.Question;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ESchool.Web.Controllers
{
    [Authorize]
    public class AnswerController : Controller
    {
        private readonly IAnswerService answerService;

        public AnswerController(IAnswerService answerService)
        {
            this.answerService = answerService;
        }

        [HttpGet]
        [Route(GlobalConstants.RouteConstants.CreateAnswerRoute)]
        public IActionResult Create(string questionId)
        {
            this.ViewData[GlobalConstants.QuestionId] = questionId;
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AnswerInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.ViewData[GlobalConstants.QuestionId] = model.QuestionId;
                return this.View();
            }

            await this.answerService.Create(model);


            return this.RedirectToAction("Index", "Home");
        }
    }
}

ESchool/ESchool.Web/Views/Answer/Create.cshtml
@model AnswerInputModel
@{
    ViewData["Title"] = "Create Answer";
    var error = ViewData[GlobalConstants.ModelError];
    var questionId = ViewData[GlobalConstants.QuestionId].ToString();
}

<section class="banner-area" id="home">
    <div class="container">
        <div class="row fullscreen d-flex align-items-center justify-content-center">
            <div class="col-md-6">
                <h2 class="d-flex justify-content-center text-light">@ViewData["Title"]</h2>
                <hr class="h2" />
                <form enctype="multipart/form-data" class="mx-auto" asp-controller="Answer" asp-action="Create" method="post">
                    @if (error != null)
                    {
                        <p class="text-danger">@error</p>
                    }
                    <div class="form-group text-center">
                        <label asp-for="AnswerText" class="text-center text-light"></label>
                        <input asp-for="AnswerText" class="form-control" placeholder="AnswerText..." />
                        <span asp-validation-for="AnswerText" class="text-danger"></span>
                    </div>

                    <div class="form-group text-center">
                        <label asp-for="IsCorrect" class="text-center text-light"></label>
                        <input asp-for="IsCorrect" class="form-control" placeholder="IsCorrect..." />
                        <span asp-validation-for="IsCorrect" class="text-danger"></span>
                    </div>

                    <input type="hidden" value="@questionId" asp-for="QuestionId" />

                    <hr class="h2" />

                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-info">Create</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</section>